# Generated by Django 4.1.1 on 2022-09-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Apointment",
            new_name="Appointment",
        ),
    ]
