# Generated by Django 4.1.1 on 2022-09-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_rename_apointment_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor_Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speciality", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor_Titles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speciality", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.doctor_speciality",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.doctor_titles"
            ),
        ),
    ]
