# Generated by Django 4.1.1 on 2022-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_doctor_speciality_doctor_titles_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor_titles",
            old_name="speciality",
            new_name="title",
        ),
    ]
