# Generated by Django 4.1.1 on 2022-09-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_rename_speciality_doctor_titles_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Doctor_Titles",
            new_name="Doctor_Title",
        ),
    ]
