# Generated by Django 4.1.1 on 2022-09-25 12:01

from django.db import migrations


def insertData(apps, schema_editor):
    Title = apps.get_model("portal", "Doctor_Title")
    Title(title="Dr.").save()
    Title(title="Prof. Dr.").save()
    Title(title="Prof. rer. nat.").save()
    Speciality = apps.get_model("portal", "Doctor_Speciality")
    Speciality(speciality="Hautarzt").save()
    Speciality(speciality="Allgemeinmedizin").save()
    Speciality(speciality="Radiologe").save()


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_rename_doctor_titles_doctor_title"),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
